chats_app/urls.py
from django.urls import path

from chats_app.views import HomeView
from . import views

app_name = 'chats_app'

urlpatterns = [
    path('', HomeView.as_view(), name="home"),
    path('chat/', views.index, name="index"),
    path('chat/<str:room_name>/', views.room, name='room'),
]

chats_project/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('userauth.urls')),
    path('', include('chats_app.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userauth/urls.py
from django.urls import path
from userauth import views
from userauth.views import ChangePasswordView

app_name = 'userauth'

urlpatterns = [
    path('login/', views.user_login_view, name="user_login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.registrationView, name="register"),
    path('edit-profile/', views.edit_profile, name="edit_profile"),
    path('password-change/', ChangePasswordView.as_view(), name="edit_password"),
]

chats_app/models.py
from django.db import models

from django.contrib.auth import get_user_model

User = get_user_model()

# Create your models here.
class Message(models.Model):
    author = models.ForeignKey(User, related_name='author_messages', on_delete=models.CASCADE)
    content = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.author.username
    
    def last_20_messages():
        return Message.objects.order_by('-timestamp').all()[:20]

chats_app/views.py
import json
from django.shortcuts import render

from django.contrib.auth.decorators import login_required

from django.utils.safestring import mark_safe

from django.views.generic import TemplateView

# Create your views here.
class HomeView(TemplateView):
    template_name = 'chats_app/home.html'

def index(request):
    return render(request, 'chats_app/index.html')

@login_required
def room(request, room_name):
    return render(request, 'chats_app/room.html', {
        'room_name_json':mark_safe(json.dumps(room_name)),
        'username':mark_safe(json.dumps(request.user.username)),
    })

templates/chats_app/base.html
<!DOCTYPE html>
{% load static %}
<html>
    <head>
        <title>
            {% block title %}
                Shaberi
            {% endblock title %}
        </title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--Favicon-->
        <link rel="icon" href="{% static 'chats_app/favicon.ico' %}" type="image/png">
        <!--Bootstrap-->
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
        <!--CSS Style-->
        <link rel="stylesheet" href="{% static 'chats_app/base.css' %}">
    </head>
    
    <body>
        
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'chats_app:home' %}">
                    <img src="{% static 'chats_app/shaberi-dark.png' %}" alt="" width="40%" height="40%" class="d-inline-block align-text-top" title="Shaberi-Home">
                </a>
            </div>
            <div class="collapse navbar-collapse flex-grow-0" id="navbarSupportedContent">
                <ul class="navbar-nav text-right">
                    {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'chats_app:index' %}">
                            <img src="{% static 'chats_app/chat-bubble.png' %}" alt="chat_room" width="23px" height="23px" title="Enter chat">
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="#">
                            <img src="{% static 'userauth/profile-bubble.png' %}" alt="Visit Profile" width="23px" height="23px" title="Visit Profile">
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'userauth:edit_profile' %}">
                            <img src="{% static 'userauth/edit-profile-bubble.png' %}" alt="Edit Profile" width="23px" height="23px" title="Edit Profile">
                        </a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'userauth:logout' %}">LogOut&nbsp;&nbsp;</a>
                    </li>
                    {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'userauth:user_login' %}">LogIN</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'userauth:register' %}">SignUP</a>
                    </li>
                    {% endif %}
                </ul>
            </div>
          </nav>
        <div class="container-fluid">
        {% block content %}
        {% endblock content %}
        </div>
        <script src="" async defer></script>
    </body>
    <div class="footer" style="background-color: #0d324d;">
        <p>Made with ❤️ using Django</p>
    </div>
</html>

templates/chats_app/home.html
{% extends 'chats_app\base.html' %}
{% load static %}
{% block content %}

<!--CSS Style-->
<link rel="stylesheet" href="{% static 'chats_app/home.css' %}">

<div class="container-fluid">
    <div class="row">
        <div class="col-3">
            <br>
            <div class="card" id="profile-card">
                <br>
                <div class="text-center">
                    <br>
                    {% if user.is_authenticated %}
                        <p>Hello <strong>{{ user.username }}</strong>!</p>
                    {% else %}
                        <p>Login to chat<br>and<br>Avail Options</p>
                    {% endif %}
                </div>
                <br>
            </div>
        </div>
        <div class="col-9">
            <div class="container-fluid">
                <div class="card about-shaberi">
                    <div class="card-body">
                        <h1>About Shaberi...</h1>
                        <p style="color: #6610f2;"> 
                            Welcome to Shaberi {{ user.username }}!<br><br>
                            喋り in japanese means to Talk 🗣️.
                            <br>
                            Using this web app you can create your <em>Private Chat Room</em>. And talk to your 
                            mates privately...
                            <br><br>
                            
                            <ol>
                                <strong>Steps to chat...</strong>
                                <li>Click the message icon on the top-right corner;</li>
                                <li>You will be redirected to the form where you have to enter the name 
                                    of the room you have to join.</li>
                                <li>Done you are in the room with your mate...</li>
                            </ol>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>


{% endblock content %}

templates/chats_app/index.html
{% extends 'chats_app\base.html' %}
{% load static %}
{% block content %}

<!--CSS Style-->
<link rel="stylesheet" href="{% static 'chats_app/index.css' %}">

{% block title %}Chat Rooms{% endblock title %}

<div class="card" id="card-room">
    <div class="card-body">
        <p>What chat room would you like to enter?<br></p>
        <input class="form-control" id="room-name-input" type="text" size="100"><br>
        <input class="btn btn-primary d-grid gap-2 col-6 mx-auto" id="room-name-submit" type="button" value="Enter">
    </div>
</div>

<script>
    document.querySelector('#room-name-input').focus();
    document.querySelector('#room-name-input').onkeyup = function(e) {
        if (e.keyCode === 13) {  // enter, return
            document.querySelector('#room-name-submit').click();
        }
    };

    document.querySelector('#room-name-submit').onclick = function(e) {
        var roomName = document.querySelector('#room-name-input').value;
        window.location.pathname = '/chat/' + roomName + '/';
    };
</script>

{% endblock content %}

templates/chats_app/room.html
{% load static %}   
<!DOCTYPE html>
<html>

    <head>
        <!--Bootstrap-->
        <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
        <link href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
        <script src="//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
        <!--Fonts-->
        <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700,300' rel='stylesheet' type='text/css'>
        <script src="https://use.typekit.net/hoy3lrg.js"></script>
        <script>try{Typekit.load({ async: true });}catch(e){}</script>
        <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/meyer-reset/2.0/reset.min.css'>
        <link rel='stylesheet prefetch' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.2/css/font-awesome.min.css'>
        <!--JQuery-->
        <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
        <!--CSS Style-->
        <link rel="stylesheet" href="{% static 'chats_app/room.css' %}">

        <title>Chat Room</title>
    </head>

    <body>
        <div id="frame">
            <div id="sidepanel">
                <div id="profile">
                    <div class="wrap">
                    <img id="profile-img" src="http://emilcarlsson.se/assets/mikeross.png" class="online" alt="" />
                    <p>{{ username }}</p>
                    <i class="fa fa-chevron-down expand-button" aria-hidden="true"></i>
                    <div id="status-options">
                        <ul>
                        <li id="status-online" class="active"><span class="status-circle"></span> <p>Online</p></li>
                        <li id="status-away"><span class="status-circle"></span> <p>Away</p></li>
                        <li id="status-busy"><span class="status-circle"></span> <p>Busy</p></li>
                        <li id="status-offline"><span class="status-circle"></span> <p>Offline</p></li>
                        </ul>
                    </div>
                    <div id="expanded">
                        <label for="twitter"><i class="fa fa-facebook fa-fw" aria-hidden="true"></i></label>
                        <input name="twitter" type="text" value="mikeross" />
                        <label for="twitter"><i class="fa fa-twitter fa-fw" aria-hidden="true"></i></label>
                        <input name="twitter" type="text" value="ross81" />
                        <label for="twitter"><i class="fa fa-instagram fa-fw" aria-hidden="true"></i></label>
                        <input name="twitter" type="text" value="mike.ross" />
                    </div>
                    </div>
                </div>
                {% comment %} <div id="search">
                    <label for=""><i class="fa fa-search" aria-hidden="true"></i></label>
                    <input type="text" placeholder="Search contacts..." />
                </div>
                <div id="contacts">
                    <ul>
                        <li class="contact">
                            <div class="wrap">
                                <span class="contact-status online"></span>
                                <img src="http://emilcarlsson.se/assets/louislitt.png" alt="" />
                                <div class="meta">
                                    <p class="name">Louis Litt</p>
                                    <p class="preview">You just got LITT up, Mike.</p>
                                </div>
                            </div>
                        </li>
                        <li class="contact active">
                            <div class="wrap">
                            <span class="contact-status busy"></span>
                            <img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" />
                            <div class="meta">
                                <p class="name">Harvey Specter</p>
                                <p class="preview">Wrong. You take the gun, or you pull out a bigger one. Or, you call their bluff. Or, you do any one of a hundred and forty six other things.</p>
                            </div>
                            </div>
                        </li>
                    </ul>
                </div> {% endcomment %}
                <div id="bottom-bar">
                    <a href="{% url 'chats_app:index' %}"><button id="addcontact"><i class="fa fa-user-plus fa-fw" aria-hidden="true"></i> <span>Create Channel</span></button></a>
                    <a href-"#"><button id="settings"><i class="fa fa-cog fa-fw" aria-hidden="true"></i> <span>Settings</span></button></a>
                </div>
            </div>
            <div class="content">
                <div class="contact-profile">
                    <img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" />
                    <p>{{ username }}</p>
                    <div class="social-media">
                        <i class="fa fa-facebook" aria-hidden="true"></i>
                        <i class="fa fa-twitter" aria-hidden="true"></i>
                        <i class="fa fa-instagram" aria-hidden="true"></i>
                    </div>
                </div>
                <div class="messages">
                    <ul id="chat-log">
                <!--
                    <li class="sent">
                        <img src="http://emilcarlsson.se/assets/mikeross.png" alt="" />
                        <p>How the hell am I supposed to get a jury to believe you when I am not even sure that I do?!</p>
                    </li>
                    <li class="replies">
                        <img src="http://emilcarlsson.se/assets/harveyspecter.png" alt="" />
                        <p>When you're backed against the wall, break the god damn thing down.</p>
                    </li>
                -->
                    </ul>
                </div>
                <div class="message-input">
                    <div class="wrap">
                        <input id="chat-message-input" type="text" placeholder="Write your message..." style="font-size:20px;" />
                        <i class="fa fa-paperclip attachment" aria-hidden="true"></i>
                        <button id="chat-message-submit" class="submit">
                            <i class="fa fa-paper-plane" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>
            </div>
        </div>
        
        <script src="{% static 'chats_app/room.js' %}"></script>
        <script src="{% static 'chats_app/reconnecting-websocket.js' %}"></script>

        <script>
            var roomName = {{ room_name_json }};
            var username = {{ username }};
            
            var chatSocket = new ReconnectingWebSocket(
                                'ws://' 
                                + window.location.host 
                                + '/ws/chat/' 
                                + roomName 
                                + '/');
            
            chatSocket.onopen = function(e) {
                fetchMessages();
            }
            
            chatSocket.onmessage = function(e) {
                var data = JSON.parse(e.data);
                if (data['command'] == 'messages') {
                    for (let i=0; i<data['messages'].length; i++) {
                        createMessage(data['messages'][i]);
                    }
                } else if (data['command'] === 'new_message') {
                    createMessage(data['message']);
                }
            };
          
            chatSocket.onclose = function(e) {
                console.error('Chat socket closed unexpectedly');
            };

            document.querySelector('#chat-message-input').onkeyup = function(e) {
                if (e.keyCode === 13) {  // enter, return
                    document.querySelector('#chat-message-submit').click();
                }
            };
        
            document.querySelector('#chat-message-submit').onclick = function(e) {
                var messageInputDom = document.getElementById('chat-message-input');
                var message = messageInputDom.value;
                chatSocket.send(JSON.stringify({
                    'command': 'new_message',
                    'message': message,
                    'from': username
                }));

                messageInputDom.value = '';
            };

            function fetchMessages() {
                chatSocket.send(JSON.stringify({'command':'fetch_messages'}));
            }

            function createMessage(data) {
                var author = data['author'];
                var msgListTag = document.createElement('li');
                var imgTag = document.createElement('img');
                var pTag = document.createElement('p');
                pTag.textContent = data.content;
                imgTag.src = 'http://emilcarlsson.se/assets/mikeross.png';
                
                if (author === username) {
                    msgListTag.className = 'sent';
                } else {
                    msgListTag.className = 'replies';
                }
                msgListTag.appendChild(imgTag);
                msgListTag.appendChild(pTag);
                document.querySelector('#chat-log').appendChild(msgListTag);        
            }
        </script>          
    </body>
</html>