chats_project/urls.py
from django.contrib import admin
from django.urls import include, path

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('userauth.urls')),
    path('', include('chats_app.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

userauth/urls.py
from django.urls import path
from userauth import views
from userauth.views import ChangePasswordView

app_name = 'userauth'

urlpatterns = [
    path('login/', views.user_login_view, name="user_login"),
    path('logout/', views.user_logout, name="logout"),
    path('register/', views.registrationView, name="register"),
    path('edit-profile/', views.edit_profile, name="edit_profile"),
    path('password-change/', ChangePasswordView.as_view(), name="edit_password"),
]

userauth/models.py
from django.db import models

from django.contrib.auth.models import User

from phonenumber_field.modelfields import PhoneNumberField
from PIL import Image

# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # bio, number, picture
    bio = models.TextField(blank=True, null=True)
    phone_number = PhoneNumberField(unique=True)
    profile_picture = models.ImageField(upload_to='profile_pics',blank=True, default='profile_pics/default_profile.png')
    
    def __str__(self):
        return str(self.user.username)
    
    def save(self, *args, **kwargs):
        super().save()
        img = Image.open(self.profile_picture.path)
        if img.height > 100 or img.width > 100:
            new_img = (100, 100)
            img.thumbnail(new_img)
            img.save(self.profile_picture.path)

userauth/forms.py
from django.contrib.auth.models import User

from django import forms
from userauth.models import Profile

from phonenumber_field.formfields import PhoneNumberField

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}), label=False)
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name*'}), label=False)
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name*'}), label=False)
    username = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username*'}), label=False)
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email'}), label=False)

    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password')


class ProfileForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Tell us who is writing Shaberi...', 'rows':"2"}), label=False)
    phone_number = PhoneNumberField()
    class Meta():
        model = Profile
        fields = ('bio', 'phone_number', 'profile_picture')


class EditUserForm(forms.ModelForm):
    first_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name*'}), label=False)
    last_name = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name*'}), label=False)
    username = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username*'}), label=False)
    email = forms.EmailField(required=True, widget=forms.EmailInput(attrs={'class':'form-control', 'placeholder':'Email'}), label=False)


    class Meta():
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')


class EditProfileForm(forms.ModelForm):
    bio = forms.CharField(widget=forms.Textarea(attrs={'class':'form-control', 'placeholder':'Tell us who is writing Shaberi...', 'rows':"2"}), label=False)
    phone_number = PhoneNumberField()
    profile_picture = forms.ImageField(widget=forms.FileInput(attrs={'class':'form-control-file'}))

    class Meta():
        model = Profile
        fields = ('bio', 'profile_picture')

userauth/views.py
from django.http import HttpResponse, HttpResponseRedirect

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import PasswordChangeView
from django.contrib.messages.views import SuccessMessageMixin

from django.shortcuts import redirect, render

from django.urls import reverse, reverse_lazy

from userauth.forms import UserForm, ProfileForm, EditProfileForm, EditUserForm
from userauth.models import Profile

# Create your views here.
@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('chats_app:home'))


def user_login_view(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('chats_app:home')) 
            else:
                return HttpResponse("ACCOUNT NOT ACTIVE")
        else:
            print("Someone tried to logon and failed...")
            print(f"User: {username} and password {password}")
            return HttpResponse("Invalid login details supplied!")
    else:
        return render(request, 'userauth/login.html', {})


def registrationView(request):
    registered = False
    # if this is the POST request we need to process the form data
    if request.method == "POST":
        # creating a form instance and populate it with data from the request: 
        user_form = UserForm(request.POST)
        profile_form = ProfileForm(request.POST)
        # checking the form is valid
        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_picture' in request.FILES:
                profile.profile_picture = request.FILES['profile_picture']
            profile.save()
            registered = True
        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = ProfileForm()
    return render(request, 'userauth/registration.html',
                            {'user_form':user_form,
                            'profile_form':profile_form,
                            'registered':registered})


@login_required
def edit_profile(request):
    Profile.objects.get_or_create(user=request.user)
    if request.method == 'POST':
        user_form = EditUserForm(request.POST, instance=request.user)
        profile_form = EditProfileForm(request.POST, request.FILES, instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, 'Your profile is updated successfully')
            return redirect(to='chats_app:home')
    else:
        user_form = EditUserForm(instance=request.user)
        profile_form = EditProfileForm(instance=request.user.profile)
    
    return render(request, 'userauth/edit_profile.html', {
        'user_form':user_form,
        'profile_form':profile_form,
    })

class ChangePasswordView(SuccessMessageMixin, PasswordChangeView):
    template_name = 'userauth/change_password.html'
    success_message = 'Successfully Changed Your Password'
    success_url = reverse_lazy('chats_app:home')

templates/userauth/change_password.html
{% extends 'chats_app/base.html' %}
{% block content %}

    <div class="form-content my-3 p-3">
        <div class="container">
            <div class="row justify-content center">
                <div class="col-lg-5">
                    <div class="card shadow-lg border-0 rounded-lg mt-0 mb-3">
                        <div class="card-header justify-content-center">
                            <h3 class="font-weight-light my-4 text-center">Change Your Password</h3>
                        </div>
                        {% if form.errors %}
                            <div class="alert alert-danger alert-dismissible" role="alert">
                                <div id="form_errors">
                                    {% for key, value in form.errors.items %}
                                        <strong>{{ value }}</strong>
                                    {% endfor %}
                                </div>
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                        {% endif %}

                        <div class="card-body">
                            <from method="POST">
                                {% csrf_token %}
                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_old_password">Old Password</label>
                                            <input type="password" name="old_password" autocomplete="new-password"
                                                    class="form-control" required id="id_old_password"
                                                    placeholder="Enter Old Password" />
                                            <span></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_new_password1">New Password</label>
                                            <input type="password" name="new_password1" autocomplete="new-password"
                                                    class="form-control" required id="id_new_password"
                                                    placeholder="Enter New Password" />
                                            <span></span>
                                        </div>
                                    </div>
                                </div>

                                <div class="form-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="form-group">
                                            <label class="small mb-1" for="id_new_password2">New Password Confirmation</label>
                                            <input type="password" name="new_password2" autocomplete="new-password"
                                                    class="form-control" required id="id_new_password2"
                                                    placeholder="Confirm New Password" />
                                        </div>
                                    </div>
                                </div>
                                <br>+
                                <div class="from-row">
                                    <div class="col-md-10 offset-md-1">
                                        <div class="from-group mt-0 md-1">
                                            <button type="submit" class="col-md-12 btn btn-dark" id="reset">Update Password</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

templates/userauth/edit_profile.html
{% extends 'chats_app/base.html' %}
{% load static %}
{% block content %}

<!--CSS Style-->
<link rel="stylesheet" href="{% static 'userauth/userauth.css' %}">

<div class="card card-edit-profile">
    {% if user.is_authenticated %}
    <h1>Edit Profile</h1><br>
    {% comment %} <div class="row my-3 p-3">
        <img class="rounded-circle account-img" src="{{ user.profile.profile_picture.url }}" style="cursor:pointer;"/>
    </div> {% endcomment %}
    {% if user_form.errors %}
        <div class="alert alert-danger alert-dismissible" role="alert">
            <div id="form_errors">
                {% for key, value in user_form.errors.items %}
                    <strong>{{ value }}</strong>
                {% endfor %}
            </div>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <button type="submit" class="btn btn-primary mb-3" id="btn-edit-profile"><span>Save Changes</span></button>
        <button type="reset" class="btn btn-dark mb-3" id="btn-reset">Reset</button>
    </form>
    <p><a href="{% url 'userauth:edit_password' %}">Change Password</a></p>
    {% else %}
    <p>You are not authorized to view this page...
        <br>
        <a href="{% url 'userauth:user_login' %}">Login</a> 
        or 
        <a href="{% url 'userauth:register' %}">Register</a> 
        First...
    </p>
    {% endif %}
</div>

{% endblock content %}

templates/userauth/login.html
{% extends 'chats_app\base.html' %}
{% load static %}
{% block content %}

<!--CSS Style-->
<link rel="stylesheet" href="{% static 'userauth/userauth.css' %}">

<br>
<div class="card text-center" id="card-login">
    <img src="{% static 'chats_app/shaberi-dark.png' %}" alt="" width="40%" height="40%" class="d-inline-block align-text-top">
    <h2>Login</h2>
    <br>
    <form action="{% url 'userauth:user_login' %}" method="POST">
        {% csrf_token %}
        <div class="form-floating">
            <input type="text" class="form-control" id="floatingInput" name="username" placeholder="Enter Username" required="">
            <label for="floatingInput username">Username:</label>
        </div>
        <br>
        <div class="form-floating">
            <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password" required="">
            <label for="floatingPassword password">Password:</label>
        </div>
        <br>
        <button type="submit" class="btn btn-primary mb-3" id="btn-login"><span>LogIn! </span></button>
        {% comment %} <input type="submit" id="btn-login" value="LogIn!"> {% endcomment %}
        <br>
        <br>
            <p>Don't have an account <a href="{% url 'userauth:register' %}">Sign UP</a> instead.</p>
        
    </form>
</div>
{% endblock content %}

templates/userauth/registration.html
{% extends 'chats_app/base.html' %}
{% load static %}
{% block content %}
<!--CSS Style-->
<link rel="stylesheet" href="{% static 'userauth/userauth.css' %}">

<br>
{% if registered %}
    <div class="card" id="after-registration">
        <h1>Thanks for Signing UP !!!</h1>
        <p>Login Once to chat <a href="{% url 'userauth:user_login' %}">Here</a></p>
    </div>
{% else %}
<div class="card text-center" id="card-register" >
    <br>
    <h3>Register here!</h3>

    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <br>
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <button type="submit" class="btn btn-primary mb-3" id="btn-login"><span>SignUP! </span></button>
    </form>
    <br>
    <p>Already have an account <a href="{% url 'userauth:user_login' %}">LogIN</a> instead.</p>
</div>
{% endif %}
<br><br>

{% endblock content %}